# Generated by Django 5.2.5 on 2025-09-19 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydata',
            options={'ordering': ['company_name'], 'verbose_name': 'Datos de la Empresa', 'verbose_name_plural': 'Datos de las Empresas'},
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='website',
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Logo de la empresa'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(max_length=266, verbose_name='Nombre de la empresa'),
        ),
    ]
