# Generated by Django 5.2.5 on 2025-09-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userverificationcode',
            table='users_verification_code',
        ),
    ]
