# Generated by Django 5.2.6 on 2025-09-17 00:21

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0001_initial'),
        ('patients_diagnoses', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la cita')),
                ('hour', models.TimeField(blank=True, null=True, verbose_name='Hora de la cita')),
                ('ailments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Padecimientos')),
                ('diagnosis', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Diagnóstico')),
                ('surgeries', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cirugías')),
                ('reflexology_diagnostics', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Diagnósticos de reflexología')),
                ('medications', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medicamentos')),
                ('observation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('initial_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicial')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('appointment_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de cita')),
                ('room', models.IntegerField(blank=True, null=True, verbose_name='Habitación/Consultorio')),
                ('social_benefit', models.BooleanField(default=True, verbose_name='Beneficio social')),
                ('payment_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle de pago')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pago')),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('appointment_status', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo')], default='PENDIENTE', max_length=20, verbose_name='Estado de la cita')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID externo en GHL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='histories_configurations.history', verbose_name='Historial')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.patient', verbose_name='Paciente')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.paymentstatus', verbose_name='Estado de pago')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.paymenttype', verbose_name='Tipo de pago')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapists.therapist', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='Número de ticket')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(default='efectivo', max_length=50, verbose_name='Método de pago')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_status.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Citas',
                'db_table': 'appointment_statuses',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'hour'], name='appointments_appointment_date_hour_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_status'], name='appointments_appointment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_ticket_number_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment_date'], name='tickets_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['appointment'], name='tickets_appointment_idx'),
        ),
    ]