# Generated by Django 5.2.6 on 2025-09-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0001_create_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de contacto en GHL'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ghl_location_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de ubicación en GHL'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ghl_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de calendario en GHL'),
        ),
    ]
