# Generated by Django 5.2.6 on 2025-09-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0002_add_ghl_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_appoint_7d154e_idx',
            old_name='appointments_appointment_date_hour_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_appoint_80fbf2_idx',
            old_name='appointments_appointment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_ticket__4c9624_idx',
            old_name='tickets_ticket_number_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_payment_5ac8c0_idx',
            old_name='tickets_payment_date_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_status_fbbf05_idx',
            old_name='tickets_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_appoint_0b3be5_idx',
            old_name='tickets_appointment_idx',
        ),
        migrations.RemoveField(
            model_name='appointmentstatus',
            name='color',
        ),
        migrations.RemoveField(
            model_name='appointmentstatus',
            name='is_active',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración de la cita (minutos)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de la cita'),
        ),
        migrations.AddField(
            model_name='appointmentstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del estado'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatus',
            index=models.Index(fields=['name'], name='appointment_name_b2e8b6_idx'),
        ),
    ]
