# Generated by Django 5.2.5 on 2025-09-24 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(default='Paciente Desconocido', max_length=200)),
                ('paciente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paciente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('ghl_event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ghl_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
