# Generated by Django 5.2.5 on 2025-09-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0002_alter_history_options_alter_paymentstatus_options_and_more'),
        ('therapists', '0001_initial'),
        ('ubi_geo', '0002_country_iso2_country_phone_code_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['first_name', 'last_name_paternal'], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.district', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='histories_configurations.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name_maternal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name_paternal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='personal_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia personal'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.province', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.region', verbose_name='Región'),
        ),
    ]
