# Generated by Django 5.2.5 on 2025-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Architect',
        ),
        migrations.AlterField(
            model_name='role',
            name='guard_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guard name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='rolehaspermission',
            unique_together={('permission', 'role')},
        ),
    ]
