# Generated by Django 5.2.5 on 2025-09-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0001_initial'),
        ('patients_diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'managed': False, 'verbose_name': 'Estado de pago', 'verbose_name_plural': 'Estados de pago'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='description',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='predeterminedprice',
            name='description',
        ),
        migrations.AddField(
            model_name='history',
            name='diu_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de DIU'),
        ),
        migrations.AddField(
            model_name='history',
            name='gestation',
            field=models.BooleanField(default=True, verbose_name='Gestación'),
        ),
        migrations.AddField(
            model_name='history',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='history',
            name='last_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Último peso'),
        ),
        migrations.AddField(
            model_name='history',
            name='menstruation',
            field=models.BooleanField(default=True, verbose_name='Menstruación'),
        ),
        migrations.AddField(
            model_name='history',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='history',
            name='private_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación privada'),
        ),
        migrations.AddField(
            model_name='history',
            name='testimony',
            field=models.BooleanField(default=True, verbose_name='Testimonio'),
        ),
        migrations.AddField(
            model_name='history',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='predeterminedprice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='predeterminedprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio'),
        ),
    ]
