# Generated by Django 5.2.5 on 2025-09-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0002_alter_history_options_alter_paymentstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentstatus',
            table='payment_status',
        ),
    ]
