# Generated by Django 5.2.5 on 2025-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ISO2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Código ISO2'),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código telefónico'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del país'),
        ),
    ]
